<?php

function employees_block_info() {
    $blocks['employees'] = array(
        'info' => t('Employee Contact Details'),
        'cache' => DRUPAL_CACHE_PER_ROLE,
    );
    return $blocks;
}

function employees_block_view($delta = '') {
    $block = array();

    switch($delta) {
        case 'employees':
            if(user_is_logged_in() && drupal_is_front_page()) {
                $block['subject'] = t('Contact Details');
                $form = drupal_get_form('employees_details_form');
                $block['content'] = drupal_render($form);
            }
    }
    return $block;

}

function employees_details_form($form, &$form_state) {
    $form['name'] = array(
        '#type' => 'textfield',
        '#title' => t('Name'),
        '#size' => 30,
        '#required' => TRUE,
    );
    $form['phone'] = array(
        '#type' => 'textfield',
        '#title' => t('Phone Number'),
        '#size' => 30,
        '#required' => TRUE,
    );
    $form['email'] = array(
        '#type' => 'textfield',
        '#title' => t('Email Address'),
        '#size' => 30,
        '#required' => TRUE,
    );
    $form['actions'] = array(
        '#type' => 'submit',
        '#value' => t('Save'),
    );
    return $form;
}

function employees_details_form_validate($form, &$form_state) {
    $email = $form_state['values']['email'];
    $phone = $form_state['values']['phone'];

    if(!Employee::is_valid_email($email)) {
        form_set_error('employees_invalid_email', t('The email address you entered is not valid.'));
    }

    if(!Employee::is_valid_phone($phone)) {
        form_set_error('employees_invalid_phone', t('The phone number you entered is not valid.'));
    }
}

function employees_details_form_submit($form, &$form_state) {
    $emp = new Employee(
            $form_state['values']['name'],
            $form_state['values']['phone'],
            $form_state['values']['email']
    );

    $emp->save();

    drupal_set_message(t('Your form has been saved.'));
}

function employees_menu() {
    $items = array();
    $items['employees/list'] = array(
        'title' => 'View Employees',
        'page callback' => 'employees_view',
        'access arguments' => array('access administration pages'),
    );
    return $items;
}

function employees_view() {
    drupal_add_css(drupal_get_path('module', 'employees') . '/employees.css');

    $header = array(
            array('data' => t('Name'), 'field' => 'name', 'sort' => 'asc'),
            array('data' => t('Email'), 'field' => 'email'),
            array('data' => t('Phone Number'), 'field' => 'phone')
    );

    $list = new EmployeesList($header);
    $items = $list->get_items();

    $rows = array();

    foreach($items as $emp) {
            $rows[] = array(
                    $emp->ename, 
                    l($emp->email,'mailto:'.$emp->email), 
                    $emp->phone
            );
    }

    $page_array['employees_view'] = array(
        '#theme' => 'table',
        '#header' => $header,
        '#rows' => $rows,
        '#attributes' => array(
            'name' => 'sort-table',
            'id' => 'employees-table',
        ),
        '#empty' => t('No employees'),
    );
    $page_array['pager'] = array(
        '#theme' => 'pager',
    );

    return $page_array;

}
